
version: '2'

networks:
  network_1.0:

services:
  ca.newput.business.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.newput.business.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.newput.business.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/93c501907b03d39c844fdcc9e1d74b2371ef3ab8bffa82f3bba9c98194f20127_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b root:root'
    volumes:
      - ./crypto-config/peerOrganizations/newput.business.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.newput.business.com
    networks:
      - network_1.0

  ca.sentient.business.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.sentient.business.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.sentient.business.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/d2405775062302d5a1c207a07f8bb5c2ff867510538bb9c65b31d6ca9fb1c26c_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b root:root'
    volumes:
      - ./crypto-config/peerOrganizations/sentient.business.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.sentient.business.com
    networks:
      - network_1.0

  ca.capitalcity.business.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.capitalcity.business.com
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.capitalcity.business.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/eab2328412a66fbeeb1fa16bde75c8912765e1a6bb7595f6afae21625e6d8bbf_sk
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start -b root:root'
    volumes:
      - ./crypto-config/peerOrganizations/capitalcity.business.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.capitalcity.business.com
    networks:
      - network_1.0

  orderer.business.com:
    container_name: orderer.business.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=BusinessOrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    volumes:
        - ./config/:/etc/hyperledger/configtx
        - ./crypto-config/ordererOrganizations/business.com/orderers/orderer.business.com/:/etc/hyperledger/msp/orderer
        - ./crypto-config/peerOrganizations/newput.business.com/peers/peer0.newput.business.com/:/etc/hyperledger/msp/peerOrg1
    networks:
      - network_1.0

  peer0.newput.business.com:
    container_name: peer0.newput.business.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.newput.business.com
      - FABRIC_LOGGING_SPEC=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=NewputMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.newput.business.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.newput.business.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.newput.business.com:7051
      
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=blockchainpractiseproject_network_1.0
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.newput.business.com:5984
      
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=root
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=root
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric 
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/newput.business.com/peers/peer0.newput.business.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/newput.business.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./sharedVolume:/etc/hyperledger/sharedVolume
    depends_on:
      - orderer.business.com
      - couchdb.newput.business.com
    networks:
      - network_1.0


  peer0.sentient.business.com:
    container_name: peer0.sentient.business.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.sentient.business.com
      - FABRIC_LOGGING_SPEC=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=SentientMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.sentient.business.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sentient.business.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sentient.business.com:7051
      
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=blockchainpractiseproject_network_1.0
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.sentient.business.com:5984
      
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=root
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=root
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/sentient.business.com/peers/peer0.sentient.business.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/sentient.business.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./sharedVolume:/etc/hyperledger/sharedVolume
  
    depends_on:
      - orderer.business.com
      - couchdb.sentient.business.com
    networks:
      - network_1.0



  peer0.capitalcity.business.com:
    container_name: peer0.capitalcity.business.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.capitalcity.business.com
      - FABRIC_LOGGING_SPEC=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_PEER_LOCALMSPID=CapitalCityMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_ADDRESS=peer0.capitalcity.business.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.capitalcity.business.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.capitalcity.business.com:7051
      
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=blockchainpractiseproject_network_1.0
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.capitalcity.business.com:5984
      
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=root
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=root
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    
    ports:
      - 9051:7051
      - 9053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/capitalcity.business.com/peers/peer0.capitalcity.business.com/msp:/etc/hyperledger/msp/peer
        - ./crypto-config/peerOrganizations/capitalcity.business.com/users:/etc/hyperledger/msp/users
        - ./config:/etc/hyperledger/configtx
        - ./sharedVolume:/etc/hyperledger/sharedVolume
        
    depends_on:
      - orderer.business.com
      - couchdb.capitalcity.business.com
    networks:
      - network_1.0

  couchdb.newput.business.com:
    container_name: couchdb.newput.business.com
    image: hyperledger/fabric-couchdb
    
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    ports:
      - 5984:5984
    networks:
      - network_1.0

  couchdb.sentient.business.com:
    container_name: couchdb.sentient.business.com
    image: hyperledger/fabric-couchdb
    
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    ports:
      - 6984:5984
    networks:
      - network_1.0

  couchdb.capitalcity.business.com:
    container_name: couchdb.capitalcity.business.com
    image: hyperledger/fabric-couchdb
    
    environment:
      - COUCHDB_USER=root
      - COUCHDB_PASSWORD=root
    ports:
      - 7984:5984
    networks:
      - network_1.0

