version: '3.1'

networks:
  network_1.0:
    external:
      name: blockchainpractiseproject_network_1.0


services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - network_1.0